inputs: TheoryOfComputation.pdf
outputs: outputs/layout_detection
tasks:
  layout_detection:
    model: layout_detection_yolo
    model_config:
      img_size: 1024
      conf_thres: 0.25
      iou_thres: 0.45
      model_path: E:/Projects/PDFKit/PDF-Extract-Kit/models/Layout/YOLO/doclayout_yolo_ft.pt
      visualize: True
